apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: gitops-sample-app-dev

images:
  - name: moabdelazem/gitops-app
    newTag: faaf577

patches:
  - path: patch-configmap.yaml
