apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: moabdelazem/gitops-app
    newTag: v1.0.0

patches:
  - path: patch-configmap.yaml
  - path: patch-deployment.yaml
