apiVersion: v1
kind: Service
metadata:
  name: gitops-sample-app
  labels:
    app: gitops-sample-app
spec:
  type: ClusterIP
  selector:
    app: gitops-sample-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
